### ISSUE TITLE
Potentially unused section in ci/pipeline.yml

### ISSUE THREAD

**Issue by aegershman** [pivotal-cf/terraforming-vsphere#11]
[There's a section in the `ci/pipeline.yml` which doesn't appear to do anything:](https://github.com/pivotal-cf/terraforming-vsphere/blob/master/ci/pipeline.yml#L28-L31)

```
shared:
- params: &om-creds
    OM_USERNAME: ((om.username))
    OM_PASSWORD: ((om.password))
```

Maybe I'm misunderstanding but does this do anything?
